title:  안범준
description: 자바, 백엔드 개발자
site_title: '안범준의 포트폴리오'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Kuan29
email: benjun99@naver.com

# absolute or relative
profile_picture: assets/images/pp.png
# Google Analytics ID
google_analytics: 